### ISSUE TITLE
the XML MOD KEY isn't updated in DB when changed

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Agent-Linux#16]
As title says, when you change the mod key name in the XML file for a game server, then you click the UPDATE CONFIGS button, the mod key isn't updated in the database ogp_config_mods table, leading in an error in different Panel pages (for sur the Update with SteamCMD page for example, where it does not find the given mod key from database).

Ticking the box Reset Old Configs and clicking Update Configs button will fix it as it will wipe everything then re add each XML files with appropriate content.

But I think this is a bug, and it should maybe update the table ogp_config_mods when you just click Update Configs button.

As Rocco changed the mod keys in different XML files recently, users start to have problems regarding this http://www.opengamepanel.org/forum/viewthread.php?thread_id=4137&rowstart=140#post_29400

**Comment by rocco27** [comment]
Thanks for reporting. I wanted to do as well. Actually it is a very very old issue.

I think when the xml file or especially the "mod key" is updated, minimum we should be able to reconfigurate the it in bottom side of the Game Monitor/Edit page, but right now only the old one is exist. So it is not possible to reconfigurate, for example set the new one.

**Comment by Zorrototo** [comment]
Wrong repo, moved it here
https://github.com/OpenGamePanel/OGP-Website/issues/223
