### ISSUE TITLE
GameQ UPDATE

### ISSUE THREAD

**Issue by ish12321** [OpenGamePanel/OGP-Agent-Linux#19]
Update GameQ to latest version

**Comment by Zorrototo** [comment]
what is the issue currently?

**Comment by rocco27** [comment]
I think he means to upgrade version 2.x to latest 3.x. New version of GameQ has new updates often. I already checked that long time ago, but the new version is total different than the old one, I could not do that.

**Comment by ish12321** [comment]
I think in old in cs1.6 if we use reunion ServerAnswerType 2 (hybrid) it cant query

**Comment by rocco27** [comment]
In OGP we have GameQ v2.0.4, which is older then what you have in [[QUESTION/REQUEST]CS1.6](https://github.com/Austinb/GameQ/issues/409).
So basicly we can't just "fix" your issue with CS 1.6, we need to upgrade GameQ library actually to have latest updates for that.

**Comment by ish12321** [comment]
That might solve many other prob too in GameQ. Is it possible for you to upgrade?

**Comment by own3mall** [comment]
There's nothing wrong with GameQ V2.

**Comment by ish12321** [comment]
There is actually.

**Comment by Zorrototo** [comment]
SO, explain in details if there is a problem, with actual proof of the problem and way to reproduce the problem. You're basically trolling at this point and should be blocked if you can not make proper reply that will be constructive. We're not twitter here, if you can not make sentences to have a proper discussion, then please refrain yourself to reply for useless messages like this. If you are willing to be constructive, please reply then.
