### ISSUE TITLE
Agent's folder is spammed by old update files.

### ISSUE THREAD

**Issue by rocco27** [OpenGamePanel/OGP-Agent-Linux#2]
Image: [http://i.imgur.com/c13W4nB.png](http://i.imgur.com/c13W4nB.png)
There is a tmp folder, why doesn't use it and why can not just remove once it finished the update process?

**Comment by own3mall** [comment]
Please verify if it's fixed in the latest version.  You'll need to delete the old zip files it downloaded manually, but it should no longer make this mess.

**Comment by rocco27** [comment]
Thank you!

**Comment by rocco27** [comment]
So I could test the fix in the first time. Now I got again a177412d75cf7c63492791db29d77c9d32fa04ea.zip file in the Agent's folder. It is compressed, but impossible to open it, says error wthile opened compressed file. The size of the file is very small, only ~3 kbytes. :)

**Comment by Zorrototo** [comment]
open it with text editor if it is so small and see content. I guess it is html 💃

**Comment by Zorrototo** [comment]
ogpGitCleanup function is not working for me. I think it is simple, it downloads file like **"a177412d75cf7c63492791db29d77c9d32fa04ea.zip"** but it tries to delete **"${REPONAME}-*"** instead of **"${REVISION}.zip"**

**Comment by own3mall** [comment]
https://github.com/OpenGamePanel/OGP-Agent-Linux/commit/de6712b6ad4fc45e4d8158b2e1634d89f834fecd 

It doesn't work like that anymore.  You have to manually delete the old zip files.  The new zip file is saved as "ogp_agent_latest.zip"

**Comment by own3mall** [comment]
It may be possible those files are coming from a few lines above where it tests the HTTP status of the file it's trying to download.  Which would mean you'd have a very small file with the contents of "200".

**Comment by own3mall** [comment]
Should be fixed now.

**Comment by Zorrototo** [comment]
yeah now it deletes all temp files thanks :)

**Comment by rocco27** [comment]
Yes, it was http status file. Thanks for fix!
