### ISSUE TITLE
MultiTheftAuto screenlog/logs_backup filled with weird characters

### ISSUE THREAD

**Issue by TAPL-93** [OpenGamePanel/OGP-Agent-Linux#21]
Apparently MultiTheftAuto servers got the screenlog/logs_backup filled with weird characters

`[23B[m[39;49m[37m[40m[H[C[0;1m[34m[47m-`

https://prnt.sc/hdngkj
https://prnt.sc/hdngql

It's just useless characters that consume the server disk space, and to make things worst the log are duplicate three times:
/home/ogp_agent/OGP_User_Files/3/logs_backup/2210117_2h52m1s.log
/usr/share/ogp_agent/screenlogs/screenlog.OGP_HOME_000000003
/usr/share/ogp_agent/screenlogs/home_id_3/2210117_2h52m1s.log

**Comment by rocco27** [comment]
What are you using to open and view the logs?

**Comment by TAPL-93** [comment]
i did simple test to save 'top' output to a file:
The file contain weird characters: top -n1 > output.txt
The file doesn't contain weird characters:  top -bn1 > output.txt

It's something to do with the way screen output saved to the file.

The weird characters are related to the colors, this how it looks like for running MultiTheftAuto server: 
https://prnt.sc/hdo2ii

**Comment by Zorrototo** [comment]
Don't enable log backup in Agent config then if you don't want... log backups in your game server folder. 
`	screen_log_local => '0',`
For the screenlogs this is how OGP works, it saves th screen output to a file, then if you restart server it move this log to the home_id_XXX folder for backup purpose and create a new file.

If you don't want these backups in the screenlogs/home_id_xxx/ folder then create a cronjob to empty this folder every hour or day.

edit: why do you talk about **top** program, when you have problem with the **screen** log output?

**Comment by TAPL-93** [comment]
@Zorrototo the issue about the weird characters, it have nothing to do with enable/disable or the way to deal with log files.

top program was a showcase about -b option which removes these weird characters from the saved output of top program, i suppose something similar can be done with screen.

Edit: the log file keep growing with these weird characters even if there's no new log lines related to the server itself.

**Comment by own3mall** [comment]
Sounds like a language or configuration issue on your end.  Using the -b flag on top has no effect... the fact your files have this stuff in them without even using panel functionality tells me that something outside of the game panel is NOT correct.  Let us know if you figure it out.

**Comment by TAPL-93** [comment]
> Using the -b flag on top has no effect

Testing on Debian 7 32bit:
root@VPS-5516:# top -bn1 > file1.txt
root@VPS-5516:# top -n1 > file2.txt
https://prnt.sc/he3gcd

> the fact your files have this stuff in them without even using panel functionality tells me that something outside of the game panel is NOT correct.

Are you talking about this? then you misunderstand because it was only to show how does the server screen of MultiTheftAuto looks like if you start it directly through SSH.

> The weird characters are related to the colors, this how it looks like for running MultiTheftAuto server:
https://prnt.sc/hdo2ii

The log I'm talking about related to the panel and i certainly showed the path of the logs that are related to the panel.

> /home/ogp_agent/OGP_User_Files/3/logs_backup/2210117_2h52m1s.log
/usr/share/ogp_agent/screenlogs/screenlog.OGP_HOME_000000003
/usr/share/ogp_agent/screenlogs/home_id_3/2210117_2h52m1s.log

Again, the log file keep growing over the time with these weird characters even if there's no new log lines related to the server itself, the reason behind this is because the screen of the server have some colors and a spinning symbol at the top and a green line at the bottom, the server screen keep refreshing and it saved to the log file with these colors which turns into weird characters if you view the log file via notepad.

**Comment by own3mall** [comment]
So, what do you want us to do about it?  It looks like the server logs that way, so you'll just have to deal with it.

See this link here:

https://answers.ros.org/question/204631/unexpected-heading-and-trailing-symbols-in-logfiles-string/
https://stackoverflow.com/questions/6306728/remove-ansi-codes-when-storing-script-output

I don't have this issue in Ubuntu.  Maybe you should complain to MultiTheftAuto developers... we're not at fault here.

**Comment by TAPL-93** [comment]
@own3mall 

```
./mta-server -h
Usage: mta-server [OPTION]

  -v                   Shows the program version
  -s                   Run server in silent mode
  -d                   Run server daemonized
  -t                   Run server with a simple console
  -f                   Run server with a standard console (Default)
  -n                   Disable the usage of ncurses (For screenlog)
  -u                   Disable output buffering and flush instantly (useful for screenlog)
  -x                   Disable simplified crash reports (To allow core dumps)
  -q                   Do not add x86/linux-libs directory to library search path and relaunch
  -D [PATH]            Use as base directory
  --config [FILE]      Alternate mtaserver.conf file
  --ip [ADDR]          Set IP address
  --port [PORT]        Set port
  --httpport [PORT]    Set http port
  --maxplayers [max]   Set maxplayers
  --novoice            Disable voice communication
```

```
./mta-server64 -h
Usage: mta-server64 [OPTION]

  -v                   Shows the program version
  -s                   Run server in silent mode
  -d                   Run server daemonized
  -t                   Run server with a simple console
  -f                   Run server with a standard console (Default)
  -n                   Disable the usage of ncurses (For screenlog)
  -u                   Disable output buffering and flush instantly (useful for screenlog)
  -x                   Disable simplified crash reports (To allow core dumps)
  -q                   Do not add x64/linux-libs directory to library search path and relaunch
  -D [PATH]            Use as base directory
  --config [FILE]      Alternate mtaserver.conf file
  --ip [ADDR]          Set IP address
  --port [PORT]        Set port
  --httpport [PORT]    Set http port
  --maxplayers [max]   Set maxplayers
  --novoice            Disable voice communication
```

@rocco27
https://github.com/OpenGamePanel/OGP-Website/commit/c4cfed15eaad2dc69ca52d84330929a65c52f264

**Comment by Zorrototo** [comment]
modify XML to have `-n`  parameter in command line, and restart server, then check if you still have the problem. Add a new line after server_exec_name https://github.com/OpenGamePanel/OGP-Website/blob/master/modules/config_games/server_configs/multitheftauto_linux64.xml#L6

` <cli_template>-n</cli_template>`

Maybe try adding -u parameter too if it is not enough (and/or -t then)

` <cli_template>-n -u</cli_template>`

**Comment by TAPL-93** [comment]
-n works, -u i can't see the difference but as it say (useful for screenlog).

Edit: old versions of multitheftauto doesn't have the parameters -n and -u  but it do have -t which removes the top bar https://prnt.sc/hfd5v2 and prevent the log file from growing over time.

```
./mta-server -v
MTA:SA Server v1.3.4-release-5836
./mta-server -h
Usage: mta-server [OPTION]

  -v                   Shows the program version
  -s                   Run server in silent mode
  -d                   Run server daemonized
  -t                   Run server with a simple console
  -f                   Run server with a standard console (Default)
  -D [PATH]            Use as base directory
  --config [FILE]      Alternate mtaserver.conf file
  --ip [ADDR]          Set IP address
  --port [PORT]        Set port
  --httpport [PORT]    Set http port
  --maxplayers [max]   Set maxplayers
  --novoice            Disable voice communication
```

**Comment by Zorrototo** [comment]
So maybe the XML simply needs the -t parameter then.

**Comment by TAPL-93** [comment]
-t only removes the top bar, -n necessary to remove "ncurses" which removes the weird characters from the saved logs.
