### ISSUE TITLE
[QUE] Regarding firewall

### ISSUE THREAD

**Issue by ish12321** [OpenGamePanel/OGP-Agent-Linux#22]
In my firewall which all ports shall I open for proper functioning of OPEN GAME PANEL? The agent and website are on same system so I'm using localhost

Getting this error in update panel :

Unable to download : https://github.com/OpenGamePanel/OGP-Website/commits/master.atom

Unable to update: String could not be parsed as XML

And in extras no modules and nothing is shown.

**Comment by rocco27** [comment]
If you just want to open all ports, then you don't need any firewall, just turn it off, but I'd not recommend to do even if it is difficult to track which ports should be open.
For webhost you can open all typical service ports what you are using.
For gamehost OGP open always the server, query and connect ports automatically. All others must be opened manually.

**Comment by ish12321** [comment]
I dont need open all ports. I just need you tell me which all should be opened. Looks like you misunderstood my question ..

**Comment by ish12321** [comment]
I mean say which ports are used by ogp?

**Comment by rocco27** [comment]
Are you using Administration/Servers/Choosed Agent/Firewall Settings? If you have UWF software, OGP can manage the firewall and the ports. You can also manage it and do manually changes.

**Comment by ish12321** [comment]
I'm using csf firewall.
Need to know which port to open for the above error

**Comment by rocco27** [comment]
This might help for standard ports: https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

GitHub uses secure http, so opening 80 is not enought, you need to open 443 https port as well.

**Comment by own3mall** [comment]
Agent port, and standard web ports for incoming and outgoing connections.

You should post on the forums rather than opening non-issues here at GitHub.
