### ISSUE TITLE
OGP AGENT showing down

### ISSUE THREAD

**Issue by ish12321** [OpenGamePanel/OGP-Agent-Linux#24]
Hey,
In my network layer I allowed all ports to my IP of the web server. However, I'm still unable to restart my ogp agent and it shows offline.
It comes up as I just now opened port 443 in agent (not sure)

Could someone pls point why is this so even after all traffic from my web server is already being accepted ?

**Comment by ish12321** [comment]
I doubt a condition that the OGP agent stucks on checking update which requires port 443??

**Comment by own3mall** [comment]
Yes, the OGP agent checks for updates and will use ports 443 and 80 depending on web server configurations.

**Comment by own3mall** [comment]
Use forums when requesting support.
