### ISSUE TITLE
php-query files way different than the current website ones

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Agent-Linux#3]
I noticed the LGSL protocol file for Agent php-query/lgsl/lgsl_protocol.php is like a really old version. I don't think I ever used it but isn't it supposed to be a copy of the one the website uses to keep compatibility with game servers? (I think this is used when you disable remote query from Panel, it uses this local query files)

It is the same with GameQ protocol files.

**Comment by own3mall** [comment]
Updated in agent, but it will always be different since it's not the panel.

**Comment by rocco27** [comment]
I'd like to ask why we have this in the Agent side? I remember we had no protocol folder in the Agent before.

**Comment by Zorrototo** [comment]
Should be that https://www.dropbox.com/s/ng6qoabvp9rbfiu/Capture%20d%27%C3%A9cran%202017-02-21%2023.14.20.png?dl=0

Thanks for the update, will try to remember that when I'll see an update on panel protocol files.

**Comment by rocco27** [comment]
Oh thanks to let me know, never seen this before. Well seems I already translated it. LOL
So then I just ask, if the Panel and the Agent are on two different servers, then I bet it is better to let the Agent to query the gameservers instead of the Panel, because of the latency? Or?

**Comment by DieFeM** [comment]
There's a situation where you would love to have this option, a FREE shared web hosting where you only can connect to other web sites on port 80, and your agent installed in a dedicated server or home computer. The trick would be binding the agent to the port 80, and let the agent do the queries directly to the game servers. PS: and yes, i've done that crap ;)

**Comment by rocco27** [comment]
Okey. thanks for the explanation. :)
