### ISSUE TITLE
agent bug?

### ISSUE THREAD

**Issue by PredatorFly** [OpenGamePanel/OGP-Agent-Linux#33]
After the update I cannot access the home folders, reinstall the agent and after a few minutes the problem appears again.
I use Ubuntu 14.

**Comment by PredatorFly** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/33920804/66616861-7b73eb80-eba0-11e9-9df6-0db4c2bed7d3.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/33920804/66616863-7c0c8200-eba0-11e9-88cc-d3bbabce7503.jpg)

**Comment by Zorrototo** [comment]
This is not the support forum, this place is to report issues that exist in OGP.
Support forum: https://www.opengamepanel.org/forum/viewthread.php?thread_id=1950
