### ISSUE TITLE
is this dead?

### ISSUE THREAD

**Issue by Succubussix** [OpenGamePanel/OGP-Agent-Linux#34]

**Comment by own3mall** [comment]
Put your ears right up to your monitor, and maybe you'll be able to hear the heartbeat.  

Seriously, what a stupid question.

**Comment by Succubussix** [comment]
I was thinking maybe they make a new version with a different name or any other hidden news.. I havent get in touch with the admin I was using this before a lot one of the admin TeamViewer me before to install mtasa hosting before when I was a kid xD. I just had free time to check if whats going on.

**Comment by Zorrototo** [comment]
The ISSUES section is to leave detailed bug reports of issues. Anyway you posted on forum too a duplicate of this question, go there if you want to continue.
