### ISSUE TITLE
"Log file missing, started new log" whenever starting SAMP server

### ISSUE THREAD

**Issue by alextwothousand** [OpenGamePanel/OGP-Agent-Linux#37]
Whenever starting my San Andreas Multiplayer server, I get this error "Log file missing, started new log". 
![image](https://user-images.githubusercontent.com/38814044/80620808-60829f00-8a3e-11ea-9fcf-f0e6cd99ef92.png)
I've tried googling and searching through the OGP forums to no avail. Reinstalling the OGP agent didn't work, I also rebooted the server as instructed to do so when reinstalling the OGP agent.

**Comment by alextwothousand** [comment]
Issue resolved.
Solution (for CentOS7):
yum install libstdc++.i686

**Comment by Zorrototo** [comment]
You wouldn't have to do that if you were following the installation guide in theory, if not then it is missing from guide, also use the forum for support https://www.opengamepanel.org/forum/index.php

**Comment by infin1tyy** [comment]
ok

**Comment by Zorrototo** [comment]
spammer, ban the account.

**Comment by alextwothousand** [comment]
What are you on about?

**Comment by Zorrototo** [comment]
You posted "ok" with an affiliate spam message with links.

**Comment by alextwothousand** [comment]
No I didn't, its because I responded through my emails. Sorry about that.

**Comment by Zorrototo** [comment]
You did it again. If it spams affiliate links then don't do it, editing your message..

**Comment by alextwothousand** [comment]
It shouldn't have happened this time. I've responded straight through github

**Comment by Zorrototo** [comment]
click my name where it says I edited, and look your message. Anyway, please don't do that, I consider it spam, personally don't like spam.

**Comment by alextwothousand** [comment]
Pardon monsieur. Au revoir !
