### ISSUE TITLE
Source games will not stop if missing map.

### ISSUE THREAD

**Issue by Codingale** [OpenGamePanel/OGP-Agent-Linux#38]
The SRCDS process will restart every time you hit stop, even manually killing it means it'll restart.

Steps to reproduce:
Install Garry's Mod Dedicated Server
Set map to `unknownmap`

Likely impacts Windows agent also.

The only fix I found was to reboot the entire machine or stopping the services and then SRCDS.

**Comment by own3mall** [comment]
Ask for help in the forums.  https://opengamepanel.org

Servers do not auto restart if stopped in the panel and the stop file is created successfully.  And also, why would you use an invalid map?
