### ISSUE TITLE
Please add a readme on how to install.

### ISSUE THREAD

**Issue by lowlevl** [OpenGamePanel/OGP-Agent-Linux#4]
The installation is pretty intuitive, but i could be great to add a little tutorial, can i send a Pull Request ?

**Comment by joshhsoj1902** [comment]
I've been meaning to get around  to adding Readme's to a bunch of my ogp repos. If you want to submit a PR for one go right ahead 😁

**Comment by own3mall** [comment]
sudo bash install.sh

The installation guide can be found on the wiki:

https://github.com/OpenGamePanel/OGP-Website/wiki

**Comment by own3mall** [comment]
And yes, you can always send a pull request.  It will be accepted if it makes sense.
