### ISSUE TITLE
Crashed server won't stop

### ISSUE THREAD

**Issue by aldemaroc** [OpenGamePanel/OGP-Agent-Linux#40]
When OGP try to stop a crashed server using rcon2 for some reason the agent never proceed to use kill -15 to stop the server.

Looks like HL2.pm is returning something that the agent does not know how to deal with as nothing after [`$rcon2->run($rconCommand);`](https://github.com/OpenGamePanel/OGP-Agent-Linux/blob/master/ogp_agent.pl#L1262) will run.

To reproduce you only need to start a Gmod server with a map that does not exist and it will hang while starting. If you use OGP's stop button nothing will happen. 

If someone that knows perl well can help me running HL2.pm manually to get it's output I can try to debug that.

**Comment by Zorrototo** [comment]
Sorry my Perl knowledge is too limited to help debug the issue.

**Comment by own3mall** [comment]
@aldemaroc Does the latest version fix your issue?
