### ISSUE TITLE
user with /usr/sbin/nologin

### ISSUE THREAD

**Issue by kossolax** [OpenGamePanel/OGP-Agent-Linux#42]
If the running user shell is set to: /usr/sbin/nologin server init script wont work. I had to add -s /bin/bash to this line:
https://github.com/OpenGamePanel/OGP-Agent-Linux/blob/b06e02e9a98aea9520d06a351f5f94cce042924e/includes/ogp_agent.init.dbn#L93

to get the OGP running.

**Comment by own3mall** [comment]
OGP is not meant to be run this way.  You'll probably have all sorts of other problems.
