### ISSUE TITLE
OGP Agent stopped working after server restart (synthax error near "linux_user_per_game_server")

### ISSUE THREAD

**Issue by ImBenny95** [OpenGamePanel/OGP-Agent-Linux#45]
Hello
I restarted my server after many months and OGP Agent just stopped working. Is it caused by an update?
It worked well for more than a year.

> ogpbot@s1:~$ bash ogp_agent_run
> <prompt>1006
> INFO: Located curl: /usr/bin/curl
> INFO: Located unzip: /usr/bin/unzip
> The agent is up to date.
> systemd detected as the init system with a directory of /lib/systemd/system.
> Agent will auto-restart if there is a crash.
> syntax error at /home/ogpbot/Cfg/Preferences.pm line 9, near "linux_user_per_game_server"
> Compilation failed in require at /home/ogpbot/ogp_agent.pl line 36.
> BEGIN failed--compilation aborted at /home/ogpbot/ogp_agent.pl line 36.
> Wed Nov  2 22:48:00 CET 2022: Agent restart in 10 seconds

This is the file:

>    screen_log_local => '1',
>    delete_logs_after => '30',
>    ogp_manages_ftp => '1',
>    ftp_method => 'proftpd',
>    ogp_autorestart_server => '1',
>    protocol_shutdown_waittime => '10',
>    proftpd_conf_path => '/etc/proftpd'
>    linux_user_per_game_server => '1',
> );

And the line:
> linux_user_per_game_server => '1',

Please help me to get my gameservers working again!
Thank you for help!

Edit:
I also opened a thread on OGP Forum before: [https://opengamepanel.org/forum/viewthread.php?thread_id=7979&pid=41344](url)
I will update both posts when I get answers,

**Comment by DieFeM** [comment]
Fixed in the following commit.
https://github.com/OpenGamePanel/OGP-Agent-Linux/commit/45c6810b521f1d308f99df2d335b2ef0898b7dd7#diff-d7c90b30d8f4fb453016bf4eaf1fdd814e961e2a9f19da12c24dedf760ea19ac

**Comment by ImBenny95** [comment]
For those who get in such a situation:
The problem was a missing comma after the previous line.
