### ISSUE TITLE
OGP panel stopped working due a recent update to ogp_agent.pl file for Linux

### ISSUE THREAD

**Issue by 1906sam** [OpenGamePanel/OGP-Agent-Linux#46]
Due to a recent changes made to ogp_agent.pl file, ogp panel has stopped working. I'm no longer able to start the game server (CSGO) from ogp panel. I'm getting the below error while starting the server:

![image](https://user-images.githubusercontent.com/3806096/205505393-7dd8c68f-2f09-4143-af5e-ebeef945ee4d.png)

Please help me understand, how can I fix this issue. Thank you :)

**Comment by Zorrototo** [comment]
https://www.opengamepanel.org/forum/viewthread.php?thread_id=7961

For any support request, open a forum thread following posting rules/requirement.
