### ISSUE TITLE
Add support for Debian latest version

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Agent-Linux#52]
User reported that installing OGP on latest Debian is not working without user intervention because of the typical package rename/substitution on later Debian version. User requested to add updated installation procedure for latest Debian version.

forum thread here: https://opengamepanel.org/forum/viewthread.php?thread_id=8119&pid=41818#post_41817

**Comment by DieFeM** [comment]
lib32gcc1 is meant for 64 bit system. All 32 bit library packages in a 64 bit system are prefixed with lib32.
So people using a 32 bit system just need to install its 32 bit counterpart, which are prefixed with just lib.
In this case libgcc1, which in most cases is instaled by default and this error can be safelly ignored.

PS: This package gives support for old games using gcc libraries, but is not a requisite for OGP itself.

**Comment by Zorrototo** [comment]
The problematic commands are from the installation procedure on OGP website, hence the issue opened here.

>Before we can install the deb package for the OGP Agent, we need to install some prerequisites by running the following commands:
>
>Code
```
sudo apt-get install libxml-parser-perl libpath-class-perl perl-modules screen rsync sudo e2fsprogs unzip subversion pure-ftpd libarchive-zip-perl libc6 libgcc1 git curl
sudo apt-get install libc6-i386 lib32gcc1
sudo apt-get install libhttp-daemon-perl
```
It may be safe to ignore but I mean following procedure outputs error, so even if this library will not be usefull to some, it may be important for others. Just reporting issue, do as you see fit as OGP Team.

PS: it seems there is also a simiklar error for Panel procedure, but user didn't give proper error yet.

**Comment by own3mall** [comment]
Sent this message to @omano via steam, but here is my plan (instructions have been updated for debian 11 / 12 on this new guide format):

Hi, I'm working on converting all of the instructions for ez install to be better and easier:  https://opengamepanel.org/install_guide/panel.html?os=debian
I also updated / fixed the steps for Debian 11 / 12 on that page
https://opengamepanel.org/install_guide/agent.html?os=debian
^^ those are agent instructions vs panel
Please review when you can and let me know what you think
I'm going to replace all of the old guides with links to those versions
Is the plan anyways...

Thoughts?

**Comment by Zorrototo** [comment]
I think being able to properly split instruction for each individual OS version would be great, instead for example having ALL Debian + ALL Ubuntu version in one page. It makes shorter and clearer instruction.

**Comment by DieFeM** [comment]
It looks like a great improvement to me. 👌
